version: "3.9"
   
services:
  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
  web:
    build: .
    command: python xblock-sdk/manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  mysql-data:
