dist: latest
language: python
python:
  - '3.8'
env:
  matrix:
    - TOXENV=django22
    - TOXENV=django30
    - TOXENV=django31
    - TOXENV=django32
  global:
    - DOCKER_USERNAME=edxbuilder
  # encrypted DOCKER_PASSWORD
    - secure: JWmtldloBZLU/+M3FlKaVGM9Kn3jMa4RTGGB84P2VIDMoCeKk6JBgdYLvt8LXx8bLV5/1JcBL+oNOWGWE7SL/AhfTKXwGq1FYdt9Nu8UqtscfIEbzBwT0MdLZtfOHqS7c7MP0ViKIcOcyj7o+vpuauJVx6MGgAzBhFH6QlVQLZU=
    - secure: ZAQze5XdSm8VEdmMdpXIxF8y163XbbnsDw+06ue5yYG41OGKcZW0u92CgzuKyjaamKJFPfST05ap9L/AxYjJ7A7bmYBUeMyMkIuHMPeJ1XOtMEtsb2x3hV5x2Z3kjxUCD/YYExDTvoGqcEbNamGZLkGPI+hJ+WXSGzw9OXqztF8=
addons:
  firefox: 52.0.1
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - sudo apt-get install xvfb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$(pwd)/geckodriver
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements/pip.txt
  - pip install tox-travis
  - pip install -r requirements/ci.txt
script:
  - xvfb-run --server-args=-ac -- tox
after_success:
  - codecov
#
#  The following actions have been switched to github CI.
#
#deploy:
#  provider: pypi
#  user: edx
#  password:
#    secure: DrrqJy3pyUC7hRESSchvtPFIiYCjHMsE1Cuq78nO3Z9Y+5Vlo8LRw76ui3lx5A1npOy/cp86eOoV01pPnOwv50ieo4xYbR6BuphLTvwaaBW3d2Hf3CRuq/fgg2vVR2QBJMCvNLOgI14D3von4PDxeiaI4Gu5hWWZJvBn+7w+inY=
#  distributions: sdist bdist_wheel
#  on:
#    tags: true
#    python: 3.8
#    condition: $TOXENV=django22
#after_deploy:
#  - make travis_docker_push
